// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://pttidjztgnqcyrsreygn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0dGlkanp0Z25xY3lyc3JleWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MjgwNzYsImV4cCI6MjA4ODQwNDA3Nn0.kWxbMyfg_kVkGWiRsSjqKBiMgcD2JdpsaFvHIolKBc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
